prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/files/carga_jpg.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/indice_png.sql
@@application/shared_components/files/logo1_png.sql
@@application/shared_components/files/logininterno101_jpg.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_requi_cot.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_repre_legal_ir.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_apoderado_ir.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_requisitos_ir.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_reqdesinscrip.sql
@@application/shared_components/logic/application_processes/mostrar_pdf_apoderado_mc.sql
@@application/shared_components/logic/application_items/global_notifica.sql
@@application/shared_components/logic/application_computations/global_notifica.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lov_bita_operaciones_comun.sql
@@application/shared_components/user_interface/lovs/lov_contribuyentes.sql
@@application/shared_components/user_interface/lovs/lov_contribuyente_cot.sql
@@application/shared_components/user_interface/lovs/lov_contribuyente_ir.sql
@@application/shared_components/user_interface/lovs/lov_contribuyente_ivc.sql
@@application/shared_components/user_interface/lovs/lov_contribuyernte_anri.sql
@@application/shared_components/user_interface/lovs/lov_empleados_plani.sql
@@application/shared_components/user_interface/lovs/lov_emple_plani2.sql
@@application/shared_components/user_interface/lovs/lov_entidades_cot.sql
@@application/shared_components/user_interface/lovs/lov_entidad_bancaria.sql
@@application/shared_components/user_interface/lovs/lov_estado.sql
@@application/shared_components/user_interface/lovs/lov_estado_inscrip.sql
@@application/shared_components/user_interface/lovs/lov_estado_tramite.sql
@@application/shared_components/user_interface/lovs/lov_garantias_nom_prove.sql
@@application/shared_components/user_interface/lovs/lov_garant_nom_prov.sql
@@application/shared_components/user_interface/lovs/lov_nombre_contrib.sql
@@application/shared_components/user_interface/lovs/lov_no_contribuyente.sql
@@application/shared_components/user_interface/lovs/lov_oficina_rn.sql
@@application/shared_components/user_interface/lovs/lov_provincia.sql
@@application/shared_components/user_interface/lovs/lov_requisitos_des.sql
@@application/shared_components/user_interface/lovs/lov_requisitos_ins.sql
@@application/shared_components/user_interface/lovs/lov_rol.sql
@@application/shared_components/user_interface/lovs/lov_si_no.sql
@@application/shared_components/user_interface/lovs/lov_tipos_puestos.sql
@@application/shared_components/user_interface/lovs/lov_tipo_apoderado.sql
@@application/shared_components/user_interface/lovs/lov_tipo_archivo.sql
@@application/shared_components/user_interface/lovs/lov_tipo_charter.sql
@@application/shared_components/user_interface/lovs/lov_tipo_contribuyente.sql
@@application/shared_components/user_interface/lovs/lov_tipo_correo.sql
@@application/shared_components/user_interface/lovs/lov_tipo_empleado.sql
@@application/shared_components/user_interface/lovs/lov_tipo_ente.sql
@@application/shared_components/user_interface/lovs/lov_tipo_identificacion.sql
@@application/shared_components/user_interface/lovs/lov_tipo_impuesto.sql
@@application/shared_components/user_interface/lovs/lov_tipo_inscripcion.sql
@@application/shared_components/user_interface/lovs/lov_tipo_local.sql
@@application/shared_components/user_interface/lovs/lov_tipo_modalidad.sql
@@application/shared_components/user_interface/lovs/lov_tipo_modulo.sql
@@application/shared_components/user_interface/lovs/lov_tipo_moneda.sql
@@application/shared_components/user_interface/lovs/lov_tipo_movimiento_cxc.sql
@@application/shared_components/user_interface/lovs/lov_tipo_mov_sit.sql
@@application/shared_components/user_interface/lovs/lov_tipo_noticia.sql
@@application/shared_components/user_interface/lovs/lov_tipo_servicio_hotel.sql
@@application/shared_components/user_interface/lovs/lov_tipo_solicitud.sql
@@application/shared_components/user_interface/lovs/lov_tipo_telefono.sql
@@application/shared_components/user_interface/lovs/lov_tipo_usuario.sql
@@application/shared_components/user_interface/lovs/lov_tip_doc_cxc.sql
@@application/shared_components/user_interface/lovs/lov_ventas.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/plugins/dynamic_action/be_ctb_alertify.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00107.sql
@@application/pages/page_00108.sql
@@application/pages/page_00109.sql
@@application/pages/page_00110.sql
@@application/pages/page_00111.sql
@@application/pages/page_00112.sql
@@application/pages/page_00113.sql
@@application/pages/page_00114.sql
@@application/pages/page_00115.sql
@@application/pages/page_00116.sql
@@application/pages/page_00117.sql
@@application/pages/page_00118.sql
@@application/pages/page_00119.sql
@@application/pages/page_00120.sql
@@application/pages/page_00121.sql
@@application/pages/page_00122.sql
@@application/pages/page_00123.sql
@@application/pages/page_00124.sql
@@application/pages/page_00125.sql
@@application/pages/page_00126.sql
@@application/pages/page_00127.sql
@@application/pages/page_00128.sql
@@application/pages/page_00129.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00133.sql
@@application/pages/page_00134.sql
@@application/pages/page_00135.sql
@@application/pages/page_00136.sql
@@application/pages/page_00137.sql
@@application/pages/page_00138.sql
@@application/pages/page_00139.sql
@@application/pages/page_00140.sql
@@application/pages/page_00141.sql
@@application/pages/page_00142.sql
@@application/pages/page_00143.sql
@@application/pages/page_00144.sql
@@application/pages/page_00145.sql
@@application/pages/page_00146.sql
@@application/pages/page_00147.sql
@@application/pages/page_00148.sql
@@application/pages/page_00149.sql
@@application/pages/page_00151.sql
@@application/pages/page_00152.sql
@@application/pages/page_00153.sql
@@application/pages/page_00154.sql
@@application/pages/page_00200.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00203.sql
@@application/pages/page_00204.sql
@@application/pages/page_00205.sql
@@application/pages/page_00206.sql
@@application/pages/page_00207.sql
@@application/pages/page_00208.sql
@@application/pages/page_00209.sql
@@application/pages/page_00210.sql
@@application/pages/page_00211.sql
@@application/pages/page_00212.sql
@@application/pages/page_00213.sql
@@application/pages/page_00214.sql
@@application/pages/page_00215.sql
@@application/pages/page_00216.sql
@@application/pages/page_00217.sql
@@application/pages/page_00218.sql
@@application/pages/page_00219.sql
@@application/pages/page_00220.sql
@@application/pages/page_00221.sql
@@application/pages/page_00222.sql
@@application/pages/page_00223.sql
@@application/pages/page_00224.sql
@@application/pages/page_00225.sql
@@application/pages/page_00226.sql
@@application/pages/page_00227.sql
@@application/pages/page_00228.sql
@@application/pages/page_00229.sql
@@application/pages/page_00230.sql
@@application/pages/page_00231.sql
@@application/pages/page_00232.sql
@@application/pages/page_00233.sql
@@application/pages/page_00234.sql
@@application/pages/page_00235.sql
@@application/pages/page_00236.sql
@@application/pages/page_00237.sql
@@application/pages/page_00238.sql
@@application/pages/page_00239.sql
@@application/pages/page_00240.sql
@@application/pages/page_00241.sql
@@application/pages/page_00242.sql
@@application/pages/page_00243.sql
@@application/pages/page_00244.sql
@@application/pages/page_00245.sql
@@application/pages/page_00246.sql
@@application/pages/page_00247.sql
@@application/pages/page_00248.sql
@@application/pages/page_00249.sql
@@application/pages/page_00250.sql
@@application/pages/page_00251.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00303.sql
@@application/pages/page_00304.sql
@@application/pages/page_00305.sql
@@application/pages/page_00306.sql
@@application/pages/page_00307.sql
@@application/pages/page_00308.sql
@@application/pages/page_00309.sql
@@application/pages/page_00310.sql
@@application/pages/page_00311.sql
@@application/pages/page_00312.sql
@@application/pages/page_00313.sql
@@application/pages/page_00314.sql
@@application/pages/page_00400.sql
@@application/pages/page_00401.sql
@@application/pages/page_00402.sql
@@application/pages/page_00403.sql
@@application/pages/page_00404.sql
@@application/pages/page_00405.sql
@@application/pages/page_00406.sql
@@application/pages/page_00407.sql
@@application/pages/page_00408.sql
@@application/pages/page_00409.sql
@@application/pages/page_00410.sql
@@application/pages/page_00411.sql
@@application/pages/page_00412.sql
@@application/pages/page_00413.sql
@@application/pages/page_00414.sql
@@application/pages/page_00415.sql
@@application/pages/page_00416.sql
@@application/pages/page_00417.sql
@@application/pages/page_00418.sql
@@application/pages/page_00419.sql
@@application/pages/page_00420.sql
@@application/pages/page_00421.sql
@@application/pages/page_00422.sql
@@application/pages/page_00423.sql
@@application/pages/page_00424.sql
@@application/pages/page_00425.sql
@@application/pages/page_00426.sql
@@application/pages/page_00427.sql
@@application/pages/page_00428.sql
@@application/pages/page_00429.sql
@@application/pages/page_00430.sql
@@application/pages/page_00431.sql
@@application/pages/page_00432.sql
@@application/pages/page_00433.sql
@@application/pages/page_00434.sql
@@application/pages/page_00435.sql
@@application/pages/page_00436.sql
@@application/pages/page_00437.sql
@@application/pages/page_00438.sql
@@application/pages/page_00439.sql
@@application/pages/page_00440.sql
@@application/pages/page_00441.sql
@@application/pages/page_00442.sql
@@application/pages/page_00443.sql
@@application/pages/page_00444.sql
@@application/pages/page_00445.sql
@@application/pages/page_00446.sql
@@application/pages/page_00447.sql
@@application/pages/page_00448.sql
@@application/pages/page_00449.sql
@@application/pages/page_00450.sql
@@application/pages/page_00451.sql
@@application/pages/page_00452.sql
@@application/pages/page_00453.sql
@@application/pages/page_00454.sql
@@application/pages/page_00455.sql
@@application/pages/page_01000.sql
@@application/pages/page_01001.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
