prompt --application/pages/page_00310
begin
--   Manifest
--     PAGE: 00310
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>5801312104779619
,p_default_application_id=>100
,p_default_id_offset=>149120778489414042
,p_default_owner=>'DESA_SIT'
);
wwv_flow_api.create_page(
 p_id=>310
,p_user_interface_id=>wwv_flow_api.id(155231128641979405)
,p_name=>unistr('310-Genera PDF Declaraci\00F3n Jurada COT')
,p_alias=>unistr('310-GENERA-PDF-DECLARACI\00D3N-JURADA-COT')
,p_page_mode=>'MODAL'
,p_step_title=>unistr('Genera PDF Declaraci\00F3n Jurada COT')
,p_reload_on_submit=>'A'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'KIMBERLYN.SOLANO'
,p_last_upd_yyyymmddhh24miss=>'20230414150625'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(576706717487784601)
,p_plug_name=>'Principal'
,p_region_template_options=>'#DEFAULT#:i-h640:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_api.id(155146499431979459)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(160745535391540648)
,p_name=>'P310_ID_DECLARACION'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(576706717487784601)
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(160745645018540649)
,p_name=>'P310_ID_REPORTE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(576706717487784601)
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(163130374856268805)
,p_name=>'DAC_SUBMIT_PAGE'
,p_event_sequence=>110
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(163130813939268806)
,p_event_id=>wwv_flow_api.id(163130374856268805)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_SUBMIT_PAGE'
,p_attribute_02=>'Y'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(163129522790268804)
,p_process_sequence=>10
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PRC_DECLA_PDF_CONCONTRATO'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'CURSOR crReport IS',
'SELECT JRD_NAME',
'FROM JRXML_REPORT_DEFINITIONS',
'WHERE JRD_ID = :P310_ID_REPORTE;',
'',
'vcName VARCHAR2(1000);',
'rParam PK_JRXML2PDF_REPGEN.tParameter;',
'lParams PK_JRXML2PDF_REPGEN.tParamlist;',
'v_periodo date;',
'bl BLOB;',
'',
'vNUMERO_PLACA VARCHAR2(20);',
'vNOMBRE_ENTIDAD VARCHAR2(100);',
'vID_TIPO_IDENTIFICACION NUMBER;',
'vCEDULA VARCHAR2(20);',
'vNOMBRE_ARRENDA VARCHAR2(80);',
'vID_TIPO_IDENTIFICA NUMBER;',
'vCEDULA_ARRE VARCHAR2(20);',
'vFECHA_INI_EXCUSION DATE;',
'vFECHA_FIN_EXCUSION DATE;',
'vDESTINO_VIAJE VARCHAR2(40);',
'vID_TIPO_PUESTO NUMBER;',
'vTOTAL_PASAJEROS NUMBER;',
'vCODIGO_MONEDA NUMBER;',
'vMONTO_TOTAL_TRANS NUMBER;',
'vIMPUESTO_PAGAR NUMBER;',
'vNOMBRE_CHOFER VARCHAR2(80);',
'vNOMBRE_GUIA VARCHAR2(80);',
'vCORREO_NOTIFICA1 VARCHAR2(50);',
'vCORREO_NOTIFICA2 VARCHAR2(50);',
'vTELEFONO1 NUMBER;',
'vTELEFONO2 NUMBER;',
'vID_OFICINA NUMBER;',
'                      ',
'       CURSOR C_DAT_DECLARA IS',
'       SELECT NUMERO_PLACA,NOMBRE_ENTIDAD,ID_TIPO_IDENTIFICACION,CEDULA,NOMBRE_ARRENDA,ID_TIPO_IDENTIFICA,CEDULA_ARRE,FECHA_INI_EXCUSION,FECHA_FIN_EXCUSION,',
'              DESTINO_VIAJE,ID_TIPO_PUESTO,TOTAL_PASAJEROS,CODIGO_MONEDA,MONTO_TOTAL_TRANS,IMPUESTO_PAGAR,NOMBRE_CHOFER,NOMBRE_GUIA,CORREO_NOTIFICA1,CORREO_NOTIFICA2,',
'              TELEFONO1,TELEFONO2,ID_OFICINA ',
'       FROM   DECLARA_CHARTER_TERRESTRE_O',
'       WHERE  ID_DECLARA_CTO = :P310_ID_DECLARACION;',
'',
'BEGIN',
'OPEN  C_DAT_DECLARA;',
'FETCH C_DAT_DECLARA INTO vNUMERO_PLACA,vNOMBRE_ENTIDAD,vID_TIPO_IDENTIFICACION,vCEDULA,vNOMBRE_ARRENDA,vID_TIPO_IDENTIFICA,vCEDULA_ARRE,vFECHA_INI_EXCUSION,',
'                         vFECHA_FIN_EXCUSION,vDESTINO_VIAJE,vID_TIPO_PUESTO,vTOTAL_PASAJEROS,vCODIGO_MONEDA,vMONTO_TOTAL_TRANS,vIMPUESTO_PAGAR,vNOMBRE_CHOFER,vNOMBRE_GUIA,vCORREO_NOTIFICA1,',
'                         vCORREO_NOTIFICA2,vTELEFONO1,vTELEFONO2,vID_OFICINA;',
'CLOSE C_DAT_DECLARA;',
'',
'OPEN crReport;',
'FETCH crReport Into vcName;',
'CLOSE crReport;',
'',
'rParam.vcName := ''pID_DECLARA_CTO'';',
'rParam.vcValue := :P310_ID_DECLARACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNUMERO_PLACA'';',
'rParam.vcValue := vNUMERO_PLACA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ENTIDAD'';',
'rParam.vcValue := vNOMBRE_ENTIDAD;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICACION'';',
'rParam.vcValue := vID_TIPO_IDENTIFICACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA'';',
'rParam.vcValue := vCEDULA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ARRENDA'';',
'rParam.vcValue := vNOMBRE_ARRENDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICA'';',
'rParam.vcValue := vID_TIPO_IDENTIFICA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA_ARRE'';',
'rParam.vcValue := vCEDULA_ARRE;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pFECHA_INI_EXCUSION'';',
'rParam.vcValue := vFECHA_INI_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pFECHA_FIN_EXCUSION'';',
'rParam.vcValue := vFECHA_FIN_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pDESTINO_VIAJE'';',
'rParam.vcValue := vDESTINO_VIAJE;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_PUESTO'';',
'rParam.vcValue := vID_TIPO_PUESTO;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTOTAL_PASAJEROS'';',
'rParam.vcValue := vTOTAL_PASAJEROS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCODIGO_MONEDA'';',
'rParam.vcValue := vCODIGO_MONEDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pMONTO_TOTAL_TRANS'';',
'rParam.vcValue := vMONTO_TOTAL_TRANS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pIMPUESTO_PAGAR'';',
'rParam.vcValue := vIMPUESTO_PAGAR;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_CHOFER'';',
'rParam.vcValue := vNOMBRE_CHOFER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_GUIA'';',
'rParam.vcValue := vNOMBRE_GUIA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA1'';',
'rParam.vcValue := vCORREO_NOTIFICA1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA2'';',
'rParam.vcValue := vCORREO_NOTIFICA2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO1'';',
'rParam.vcValue := vTELEFONO1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO2'';',
'rParam.vcValue := vTELEFONO2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_OFICINA'';',
'rParam.vcValue := vID_OFICINA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pUsuario'';',
'rParam.vcValue := :APP_USER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'bl := PK_JRXML2PDF_REPGEN.FK_RUN(i_vcName=>vcName,i_lParams=>lParams);',
'COMMIT;',
'PK_JRXML2PDF_REPGEN.PR_SHOW_REPORT(bl);',
'APEX_APPLICATION.STOP_APEX_ENGINE;',
'END;'))
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'P310_ID_REPORTE'
,p_process_when_type=>'VAL_OF_ITEM_IN_COND_EQ_COND2'
,p_process_when2=>'1220'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(163230074870154204)
,p_process_sequence=>20
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PRC_DECLA_PDF_SINCONTRATO'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'CURSOR crReport IS',
'SELECT JRD_NAME',
'FROM JRXML_REPORT_DEFINITIONS',
'WHERE JRD_ID = :P310_ID_REPORTE;',
'',
'vcName VARCHAR2(1000);',
'rParam PK_JRXML2PDF_REPGEN.tParameter;',
'lParams PK_JRXML2PDF_REPGEN.tParamlist;',
'v_periodo date;',
'bl BLOB;',
'',
'vNUMERO_PLACA VARCHAR2(20);',
'vNOMBRE_ENTIDAD VARCHAR2(100);',
'vID_TIPO_IDENTIFICACION NUMBER;',
'vCEDULA VARCHAR2(20);',
'--vNOMBRE_ARRENDA VARCHAR2(80);',
'--vID_TIPO_IDENTIFICA NUMBER;',
'--vCEDULA_ARRE VARCHAR2(20);',
'vFECHA_INI_EXCUSION DATE;',
'vFECHA_FIN_EXCUSION DATE;',
'vDESTINO_VIAJE VARCHAR2(40);',
'vID_TIPO_PUESTO NUMBER;',
'vTOTAL_PASAJEROS NUMBER;',
'vCODIGO_MONEDA NUMBER;',
'vMONTO_TOTAL_TRANS NUMBER;',
'vIMPUESTO_PAGAR NUMBER;',
'vNOMBRE_CHOFER VARCHAR2(80);',
'vNOMBRE_GUIA VARCHAR2(80);',
'vCORREO_NOTIFICA1 VARCHAR2(50);',
'vCORREO_NOTIFICA2 VARCHAR2(50);',
'vTELEFONO1 NUMBER;',
'vTELEFONO2 NUMBER;',
'vID_OFICINA NUMBER;',
'                      ',
'       CURSOR C_DAT_DECLARA IS',
'       SELECT NUMERO_PLACA,NOMBRE_ENTIDAD,ID_TIPO_IDENTIFICACION,CEDULA,/*NOMBRE_ARRENDA,ID_TIPO_IDENTIFICA,CEDULA_ARRE,*/FECHA_INI_EXCUSION,FECHA_FIN_EXCUSION,',
'              DESTINO_VIAJE,ID_TIPO_PUESTO,TOTAL_PASAJEROS,CODIGO_MONEDA,MONTO_TOTAL_TRANS,IMPUESTO_PAGAR,NOMBRE_CHOFER,NOMBRE_GUIA,CORREO_NOTIFICA1,CORREO_NOTIFICA2,',
'              TELEFONO1,TELEFONO2,ID_OFICINA ',
'       FROM   DECLARA_CHARTER_TERRESTRE_O',
'       WHERE  ID_DECLARA_CTO = :P310_ID_DECLARACION;',
'',
'BEGIN',
'OPEN  C_DAT_DECLARA;',
'FETCH C_DAT_DECLARA INTO vNUMERO_PLACA,vNOMBRE_ENTIDAD,vID_TIPO_IDENTIFICACION,vCEDULA,/*vNOMBRE_ARRENDA,vID_TIPO_IDENTIFICA,vCEDULA_ARRE,*/vFECHA_INI_EXCUSION,',
'                         vFECHA_FIN_EXCUSION,vDESTINO_VIAJE,vID_TIPO_PUESTO,vTOTAL_PASAJEROS,vCODIGO_MONEDA,vMONTO_TOTAL_TRANS,vIMPUESTO_PAGAR,vNOMBRE_CHOFER,vNOMBRE_GUIA,vCORREO_NOTIFICA1,',
'                         vCORREO_NOTIFICA2,vTELEFONO1,vTELEFONO2,vID_OFICINA;',
'CLOSE C_DAT_DECLARA;',
'',
'OPEN crReport;',
'FETCH crReport Into vcName;',
'CLOSE crReport;',
'',
'rParam.vcName := ''pID_DECLARA_CTO'';',
'rParam.vcValue := :P310_ID_DECLARACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNUMERO_PLACA'';',
'rParam.vcValue := vNUMERO_PLACA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ENTIDAD'';',
'rParam.vcValue := vNOMBRE_ENTIDAD;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICACION'';',
'rParam.vcValue := vID_TIPO_IDENTIFICACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA'';',
'rParam.vcValue := vCEDULA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ARRENDA'';',
'/*rParam.vcValue := vNOMBRE_ARRENDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICA'';',
'rParam.vcValue := vID_TIPO_IDENTIFICA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA_ARRE'';',
'rParam.vcValue := vCEDULA_ARRE;',
'lParams(lParams.COUNT+1):=rParam;*/',
'',
'rParam.vcName := ''pFECHA_INI_EXCUSION'';',
'rParam.vcValue := vFECHA_INI_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pFECHA_FIN_EXCUSION'';',
'rParam.vcValue := vFECHA_FIN_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pDESTINO_VIAJE'';',
'rParam.vcValue := vDESTINO_VIAJE;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_PUESTO'';',
'rParam.vcValue := vID_TIPO_PUESTO;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTOTAL_PASAJEROS'';',
'rParam.vcValue := vTOTAL_PASAJEROS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCODIGO_MONEDA'';',
'rParam.vcValue := vCODIGO_MONEDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pMONTO_TOTAL_TRANS'';',
'rParam.vcValue := vMONTO_TOTAL_TRANS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pIMPUESTO_PAGAR'';',
'rParam.vcValue := vIMPUESTO_PAGAR;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_CHOFER'';',
'rParam.vcValue := vNOMBRE_CHOFER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_GUIA'';',
'rParam.vcValue := vNOMBRE_GUIA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA1'';',
'rParam.vcValue := vCORREO_NOTIFICA1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA2'';',
'rParam.vcValue := vCORREO_NOTIFICA2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO1'';',
'rParam.vcValue := vTELEFONO1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO2'';',
'rParam.vcValue := vTELEFONO2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_OFICINA'';',
'rParam.vcValue := vID_OFICINA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pUsuario'';',
'rParam.vcValue := :APP_USER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'bl := PK_JRXML2PDF_REPGEN.FK_RUN(i_vcName=>vcName,i_lParams=>lParams);',
'COMMIT;',
'PK_JRXML2PDF_REPGEN.PR_SHOW_REPORT(bl);',
'APEX_APPLICATION.STOP_APEX_ENGINE;',
'END;'))
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'P310_ID_REPORTE'
,p_process_when_type=>'VAL_OF_ITEM_IN_COND_EQ_COND2'
,p_process_when2=>'1240'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(167972832223571019)
,p_process_sequence=>30
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PRC_DECLA_PDF_CONCONTRATO_TTR'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'CURSOR crReport IS',
'SELECT JRD_NAME',
'FROM JRXML_REPORT_DEFINITIONS',
'WHERE JRD_ID = :P310_ID_REPORTE;',
'',
'vcName VARCHAR2(1000);',
'rParam PK_JRXML2PDF_REPGEN.tParameter;',
'lParams PK_JRXML2PDF_REPGEN.tParamlist;',
'v_periodo date;',
'bl BLOB;',
'',
'vNUMERO_PLACA VARCHAR2(20);',
'vNOMBRE_ENTIDAD VARCHAR2(100);',
'vID_TIPO_IDENTIFICACION NUMBER;',
'vCEDULA VARCHAR2(20);',
'vNOMBRE_ARRENDA VARCHAR2(80);',
'vID_TIPO_IDENTIFICA NUMBER;',
'vCEDULA_ARRE VARCHAR2(20);',
'vFECHA_INI_EXCUSION DATE;',
'vFECHA_FIN_EXCUSION DATE;',
'vDESTINO_VIAJE VARCHAR2(40);',
'vID_TIPO_PUESTO NUMBER;',
'vTOTAL_PASAJEROS NUMBER;',
'vCODIGO_MONEDA NUMBER;',
'vMONTO_TOTAL_TRANS NUMBER;',
'vIMPUESTO_PAGAR NUMBER;',
'vNOMBRE_CHOFER VARCHAR2(80);',
'vNOMBRE_GUIA VARCHAR2(80);',
'vCORREO_NOTIFICA1 VARCHAR2(50);',
'vCORREO_NOTIFICA2 VARCHAR2(50);',
'vTELEFONO1 NUMBER;',
'vTELEFONO2 NUMBER;',
'vID_OFICINA NUMBER;',
'',
'CURSOR C_DAT_DECLARA IS',
'       SELECT NUMERO_PLACA,NOMBRE_ENTIDAD,ID_TIPO_IDENTIFICACION,CEDULA,NOMBRE_ARRENDA,ID_TIPO_IDENTIFICA,CEDULA_ARRE,FECHA_INI_EXCUSION,FECHA_FIN_EXCUSION,',
'              DESTINO_VIAJE,ID_TIPO_PUESTO,TOTAL_PASAJEROS,CODIGO_MONEDA,MONTO_TOTAL_TRANS,IMPUESTO_PAGAR,NOMBRE_CHOFER,NOMBRE_GUIA,CORREO_NOTIFICA1,CORREO_NOTIFICA2,',
'              TELEFONO1,TELEFONO2,ID_OFICINA ',
'       FROM   DECLARA_CHARTER_TERRESTRE_O',
'       WHERE  ID_DECLARA_CTO = :P310_ID_DECLARACION;',
'BEGIN',
'OPEN  C_DAT_DECLARA;',
'FETCH C_DAT_DECLARA INTO vNUMERO_PLACA,vNOMBRE_ENTIDAD,vID_TIPO_IDENTIFICACION,vCEDULA,vNOMBRE_ARRENDA,vID_TIPO_IDENTIFICA,vCEDULA_ARRE,vFECHA_INI_EXCUSION,',
'                         vFECHA_FIN_EXCUSION,vDESTINO_VIAJE,vID_TIPO_PUESTO,vTOTAL_PASAJEROS,vCODIGO_MONEDA,vMONTO_TOTAL_TRANS,vIMPUESTO_PAGAR,vNOMBRE_CHOFER,vNOMBRE_GUIA,vCORREO_NOTIFICA1,',
'                         vCORREO_NOTIFICA2,vTELEFONO1,vTELEFONO2,vID_OFICINA;',
'CLOSE C_DAT_DECLARA;',
'',
'',
'OPEN crReport;',
'FETCH crReport Into vcName;',
'CLOSE crReport;',
'',
'rParam.vcName := ''pID_DECLARA_CTO'';',
'rParam.vcValue := :P310_ID_DECLARACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNUMERO_PLACA'';',
'rParam.vcValue := vNUMERO_PLACA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ENTIDAD'';',
'rParam.vcValue := vNOMBRE_ENTIDAD;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICACION'';',
'rParam.vcValue := vID_TIPO_IDENTIFICACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA'';',
'rParam.vcValue := vCEDULA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ARRENDA'';',
'rParam.vcValue := vNOMBRE_ARRENDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICA'';',
'rParam.vcValue := vID_TIPO_IDENTIFICA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA_ARRE'';',
'rParam.vcValue := vCEDULA_ARRE;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pFECHA_INI_EXCUSION'';',
'rParam.vcValue := vFECHA_INI_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pFECHA_FIN_EXCUSION'';',
'rParam.vcValue := vFECHA_FIN_EXCUSION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pDESTINO_VIAJE'';',
'rParam.vcValue := vDESTINO_VIAJE;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_PUESTO'';',
'rParam.vcValue := vID_TIPO_PUESTO;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTOTAL_PASAJEROS'';',
'rParam.vcValue := vTOTAL_PASAJEROS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCODIGO_MONEDA'';',
'rParam.vcValue := vCODIGO_MONEDA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pMONTO_TOTAL_TRANS'';',
'rParam.vcValue := vMONTO_TOTAL_TRANS;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pIMPUESTO_PAGAR'';',
'rParam.vcValue := vIMPUESTO_PAGAR;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_CHOFER'';',
'rParam.vcValue := vNOMBRE_CHOFER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_GUIA'';',
'rParam.vcValue := vNOMBRE_GUIA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA1'';',
'rParam.vcValue := vCORREO_NOTIFICA1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA2'';',
'rParam.vcValue := vCORREO_NOTIFICA2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO1'';',
'rParam.vcValue := vTELEFONO1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO2'';',
'rParam.vcValue := vTELEFONO2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_OFICINA'';',
'rParam.vcValue := vID_OFICINA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pUsuario'';',
'rParam.vcValue := :APP_USER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'bl := PK_JRXML2PDF_REPGEN.FK_RUN(i_vcName=>vcName,i_lParams=>lParams);',
'COMMIT;',
'PK_JRXML2PDF_REPGEN.PR_SHOW_REPORT(bl);',
'APEX_APPLICATION.STOP_APEX_ENGINE;',
'END;'))
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'P310_ID_REPORTE'
,p_process_when_type=>'VAL_OF_ITEM_IN_COND_EQ_COND2'
,p_process_when2=>'1282'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(167972951090571020)
,p_process_sequence=>40
,p_process_point=>'ON_SUBMIT_BEFORE_COMPUTATION'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'PRC_DECLA_PDF_SINCONTRATO_TTR'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'CURSOR crReport IS',
'SELECT JRD_NAME',
'FROM JRXML_REPORT_DEFINITIONS',
'WHERE JRD_ID = :P310_ID_REPORTE;',
'',
'vcName VARCHAR2(1000);',
'rParam PK_JRXML2PDF_REPGEN.tParameter;',
'lParams PK_JRXML2PDF_REPGEN.tParamlist;',
'v_periodo date;',
'bl BLOB;',
'',
'vNUMERO_PLACA VARCHAR2(20);',
'vNOMBRE_ENTIDAD VARCHAR2(100);',
'vID_TIPO_IDENTIFICACION NUMBER;',
'vCEDULA VARCHAR2(20);',
'vNOMBRE_ARRENDA VARCHAR2(80);',
'vID_TIPO_IDENTIFICA NUMBER;',
'vCEDULA_ARRE VARCHAR2(20);',
'vFECHA_INI_EXCUSION DATE;',
'vFECHA_FIN_EXCUSION DATE;',
'vDESTINO_VIAJE VARCHAR2(40);',
'vID_TIPO_PUESTO NUMBER;',
'vTOTAL_PASAJEROS NUMBER;',
'vCODIGO_MONEDA NUMBER;',
'vMONTO_TOTAL_TRANS NUMBER;',
'vIMPUESTO_PAGAR NUMBER;',
'vNOMBRE_CHOFER VARCHAR2(80);',
'vNOMBRE_GUIA VARCHAR2(80);',
'vCORREO_NOTIFICA1 VARCHAR2(50);',
'vCORREO_NOTIFICA2 VARCHAR2(50);',
'vTELEFONO1 NUMBER;',
'vTELEFONO2 NUMBER;',
'vID_OFICINA NUMBER;',
'',
'CURSOR C_DAT_DECLARA IS',
'       SELECT NUMERO_PLACA,NOMBRE_ENTIDAD,ID_TIPO_IDENTIFICACION,CEDULA,NOMBRE_ARRENDA,ID_TIPO_IDENTIFICA,CEDULA_ARRE,FECHA_INI_EXCUSION,FECHA_FIN_EXCUSION,',
'              DESTINO_VIAJE,ID_TIPO_PUESTO,TOTAL_PASAJEROS,CODIGO_MONEDA,MONTO_TOTAL_TRANS,IMPUESTO_PAGAR,NOMBRE_CHOFER,NOMBRE_GUIA,CORREO_NOTIFICA1,CORREO_NOTIFICA2,',
'              TELEFONO1,TELEFONO2,ID_OFICINA ',
'       FROM   DECLARA_CHARTER_TERRESTRE_O',
'       WHERE  ID_DECLARA_CTO = :P310_ID_DECLARACION;',
'',
'BEGIN',
'OPEN  C_DAT_DECLARA;',
'FETCH C_DAT_DECLARA INTO vNUMERO_PLACA,vNOMBRE_ENTIDAD,vID_TIPO_IDENTIFICACION,vCEDULA,vNOMBRE_ARRENDA,vID_TIPO_IDENTIFICA,vCEDULA_ARRE,vFECHA_INI_EXCUSION,',
'                         vFECHA_FIN_EXCUSION,vDESTINO_VIAJE,vID_TIPO_PUESTO,vTOTAL_PASAJEROS,vCODIGO_MONEDA,vMONTO_TOTAL_TRANS,vIMPUESTO_PAGAR,vNOMBRE_CHOFER,vNOMBRE_GUIA,vCORREO_NOTIFICA1,',
'                         vCORREO_NOTIFICA2,vTELEFONO1,vTELEFONO2,vID_OFICINA;',
'CLOSE C_DAT_DECLARA;',
'',
'',
'OPEN crReport;',
'FETCH crReport Into vcName;',
'CLOSE crReport;',
'',
'rParam.vcName := ''pID_DECLARA_CTO'';',
'rParam.vcValue := :P310_ID_DECLARACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNUMERO_PLACA'';',
'rParam.vcValue := vNUMERO_PLACA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pNOMBRE_ENTIDAD'';',
'rParam.vcValue := vNOMBRE_ENTIDAD;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_TIPO_IDENTIFICACION'';',
'rParam.vcValue := vID_TIPO_IDENTIFICACION;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCEDULA'';',
'rParam.vcValue := vCEDULA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA1'';',
'rParam.vcValue := vCORREO_NOTIFICA1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pCORREO_NOTIFICA2'';',
'rParam.vcValue := vCORREO_NOTIFICA2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO1'';',
'rParam.vcValue := vTELEFONO1;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pTELEFONO2'';',
'rParam.vcValue := vTELEFONO2;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pID_OFICINA'';',
'rParam.vcValue := vID_OFICINA;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'rParam.vcName := ''pUsuario'';',
'rParam.vcValue := :APP_USER;',
'lParams(lParams.COUNT+1):=rParam;',
'',
'bl := PK_JRXML2PDF_REPGEN.FK_RUN(i_vcName=>vcName,i_lParams=>lParams);',
'COMMIT;',
'PK_JRXML2PDF_REPGEN.PR_SHOW_REPORT(bl);',
'APEX_APPLICATION.STOP_APEX_ENGINE;',
'END;'))
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when=>'P310_ID_REPORTE'
,p_process_when_type=>'VAL_OF_ITEM_IN_COND_EQ_COND2'
,p_process_when2=>'1302'
);
wwv_flow_api.component_end;
end;
/
